### ISSUE TITLE
Проверить с валютой

### ISSUE THREAD

**Issue by sunnycreature** [gsbelarus/gdmn-bot#18]
Российскуй рубль не загрузился
![image](https://user-images.githubusercontent.com/12336960/83894647-3bc6c900-a75a-11ea-82db-f4fe87649f1c.png)

В описании расчетного листка не верно указывается год даты курса
![image](https://user-images.githubusercontent.com/12336960/83894582-281b6280-a75a-11ea-88c8-f41f61713c9d.png)

**Comment by gsbelarus** [comment]
Код RUB я подправил. Надо с датой перепроверить и закрыть или исправить.
