### ISSUE TITLE
Опять даты строкой из гедымина передаются неправильно

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-bot#27]
Это из последнего списка по БМКК:
```json
    "188129360_534865013": {
      "firstName": "Виктор",
      "lastName": "XXXX",
      "patrName": "Константинович",
      "birthday": "1962.9.29",
```
Должен быть месяц 09. 

И надо решить, если мы передаем даты как YYYY.MM.DD, то проверить чтобы везде-везде они передавались именно в таком формате.

**Comment by sunnycreature** [comment]
Сделала в employee 
![image](https://user-images.githubusercontent.com/12336960/84738157-0fa91480-afb2-11ea-80ab-7688a8c513e3.png)
В payslip
![image](https://user-images.githubusercontent.com/12336960/84738202-2fd8d380-afb2-11ea-9267-8df5fa37630c.png)
