### ISSUE TITLE
демо-данные

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-bot#30]
Взять наиболее навороченные данные по сотруднику из действующего предприятия и на основе них создать демо-данные. Чтобы когда будем показывать кому-нибудь не надо это было делать на реальных данных.

**Comment by sunnycreature** [comment]
Моя организация
123456789
5879 за июнь

**Comment by gsbelarus** [comment]
а в демо организации меню тоже есть?
