### ISSUE TITLE
слишком много цифр

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-bot#58]
В сравнительном листке слишком много цифр из-за чего информация не очень читабельна. Я бы здесь округлял до целого рубля и выводил без копеек:

![image](https://user-images.githubusercontent.com/5175764/86536710-7acf7200-bef2-11ea-8580-df2478838007.png)

**Comment by sunnycreature** [comment]
![image](https://user-images.githubusercontent.com/12336960/87009691-37188900-c1ce-11ea-8125-da8f67a98d63.png)
