### ISSUE TITLE
По столовой

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-bot#70]
1. Кнопку лучше назвать *Меню столовой* или *Столовая*. Так будет понятнее.
2. У нас может быть три ситуации: а) кнопка видна, но на предприятии не используется наш общепит и данные не передаются, б) кнопка видна, но меню на сегодня нет (например, еще не передали), в) кнопка видна, меню есть.

В первом случае надо понятно сообщить пользователю, что меню столовой можно просмотреть, только если на предприятии установлена программа "Гедымин: Общепит".

Во втором надо сообщить что меню на сегодня еще не было загружено. Попробуйте позже.

В третьем показываем меню столовой и возвращаемся в главное меню программы.

**Comment by sunnycreature** [comment]
Сделано
